import re                                                                        
email_data = "sudham <sudhamkshetty7@gmail.com>, amar <amaralva.gmail.com>, shetty <sudhamkshetty7@gmail.com>, ashu  <ashishhmsagar@gmail.com>, ashish01 <ashishhmsagar@gmail.com>"
result=re.search("ash[i, u]", email_data)
print(result)
result = re.search("Ash[i, u]", email_data, re.IGNORECASE)
print(result)
result = re.search("ash[a-z]", email_data)
print(result)
result = re.findall("ash[a-z]", email_data)
print(result)
result = re.search("ash[a-z]+", email_data)
print(result)
result = re.search("ash[a-z]+[0-9]+", email_data)
print(result)
result = re.search(r"[A-Za-z0-9_]+@[A-Za-z0-9]+\.[A-Za-z0-9]+", email_data)
print(result)
result = re.findall(r"[A-Za-z0-9_]+@[A-Za-z0-9]+\.[A-Za-z0-9]+", email_data)
print(result)
result = re.findall(r"\w+@\w+\.\w+", email_data)
print(result)
